Update default config
yiisoft/db-migration pull request #222
Opened 2023-10-19 16:21 UTC by Tigrov

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | -

2023-10-19 16:34 UTC, samdark approved these changes

2023-10-20 06:59 UTC, vjik requested changes

2023-10-20 06:59 UTC, vjik commented on docs/en/usage-with-symfony-console.md
> +            MigrationInformerInterface::class => ConsoleMigrationInformer::class,
To need to fix in configuration also: https://github.com/yiisoft/db-migration/blob/master/config/di-console.php#L20

2023-10-21 07:17 UTC, vjik approved these changes

2023-10-21 07:17 UTC, merged