Improve informing
yiisoft/db-migration pull request #225
Opened 2023-10-21 10:38 UTC by Tigrov

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | -

2023-10-22 11:27 UTC, vjik requested changes

2023-10-22 11:27 UTC, vjik commented on src/Service/MigrationService.php
> +     * @psalm-param array<int, class-string> $classes
```suggestion
     * @psalm-param list<class-string> $classes
```

2023-10-22 11:27 UTC, vjik commented on src/Service/MigrationService.php
> +     * @psalm-return array<int, MigrationInterface>
```suggestion
     * @psalm-return list<MigrationInterface>
```

2023-10-22 11:27 UTC, vjik commented on src/Service/MigrationService.php
> +     * @psalm-param array<int, class-string> $classes
```suggestion
     * @psalm-param list<class-string> $classes
```

2023-10-22 11:27 UTC, vjik commented on src/Service/MigrationService.php
> +     * @psalm-return array<int, RevertibleMigrationInterface>
```suggestion
     * @psalm-return list<RevertibleMigrationInterface>
```

2023-10-23 17:52 UTC, samdark approved these changes

2023-10-24 12:12 UTC, vjik approved these changes

2023-10-24 12:12 UTC, merged