Fix #227
yiisoft/db-migration pull request #250
Opened 2023-12-21 17:23 UTC by viktorprogger

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | #227

2023-12-21 17:53 UTC, vjik requested changes
Need tests and line in changelog

2023-12-23 13:28 UTC, samdark approved these changes

2023-12-23 13:52 UTC, vjik approved these changes

2023-12-23 18:38 UTC, merged

2023-12-23 18:38 UTC, samdark commented
👍